### ISSUE TITLE
Quick Fixes:  Add word "is" and Correct to Contraction"It's" 

### ISSUE THREAD

**Issue by ccklight** [learn-co-curriculum/html-images-lab#2]
1.  Missing word "is"
************************
The src attribute always necessary, as without it, the img tag would have nothing to display.

2. Line 2, Change "Its" to "It's" 
********************************
Reinforce Our Understanding Of The Image Tag Through Creation
Its time to practice creating some images! For this challenge, feel free to use any images you'd like - the tests are looking for the correct

**Comment by rrcobb** [comment]
Duplicate of #1
